### ISSUE TITLE
Convert Date Time to epoch

### ISSUE THREAD

**Issue by jrock2004** [snooze92/alfred-epoch-converter#1]
Would love to see a way to do something like the follow and get it in epoch format

```bash
ts 2019-12-23 05:50
```

Thoughts?

**Comment by snooze92** [comment]
I haven’t needed that feature just yet, but it seems like a great idea, a good fit for this workflow, and something that shouldn’t be too hard to add.

Do you want to take a stab at it? Otherwise I can probably find some time soon.

**Comment by snooze92** [comment]
I decided to create [release 1.0.0](https://github.com/snooze92/alfred-epoch-converter/releases/tag/1.0.0) so that everyone gets the clipboard support, and to support your request. Let me know what you think!

**Comment by jrock2004** [comment]
How do you upgrade?

**Comment by snooze92** [comment]
I bumped the version both in Git and Packal, so I expect any automated upgrade that goes via Git or Packal should work. Alternatively, you can delete the current workflow from your current preferences, download the latest file [epoch-converter-1_0_0.alfredworkflow](https://github.com/snooze92/alfred-epoch-converter/releases/download/1.0.0/epoch-converter-1_0_0.alfredworkflow) and install the latest version from scatch.
