### ISSUE TITLE
Unable to open workflow on macOS 13.2

### ISSUE THREAD

**Issue by leoleec** [snooze92/alfred-epoch-converter#12]
macOS: 13.2
alfred: 5.0.6
workflow: 1.0.3
python: 3.7.4

I couldn't open this alfred workflow after I've upgraded to macOS 13.2 (Ventura).
Please let me know how to fix this issue :-)

**Comment by snooze92** [comment]
I'm using macOS Ventura as well, with similar versions of Python and the workflow, but have not upgraded to Alfred 5 yet. I will try that soon.

In the mean time, I would need to hear more details about your issue (e.g. what symptoms do you see, are you able to grab some logs?) to be able to help!

**Comment by snooze92** [comment]
It still works for me...
- macOS: 13.2 (22D49)
- Alfred: 5.0.6 (2110)
- Workflow: 1.0.3 (411295f)
- Python: 3.9.6

<img width="756" alt="image" src="https://user-images.githubusercontent.com/3275550/215700016-8c07219f-d65c-4316-a35e-3b420f49b9a3.png">

I guess it could be an issue with the Python version difference?

You can run the workflow manually on your command-line, to debug. For instance:

```
$ /usr/bin/python3 epoch.py ""
.
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>1675152725</title><subtitle>Current timestamp (s)</subtitle><arg>1675152725</arg><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns</icon></item><item valid="yes"><title>1675152725204</title><subtitle>Current timestamp (ms)</subtitle><arg>1675152725204</arg><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns</icon></item><item valid="yes"><title>1675152725204069</title><subtitle>Current timestamp (&#181;s)</subtitle><arg>1675152725204069</arg><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns</icon></item><item valid="yes"><title>1675152725204073984</title><subtitle>Current timestamp (ns)</subtitle><arg>1675152725204073984</arg><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns</icon></item></items>
9:12:05 workflow.py:2070 ERROR    __init__() got an unexpected keyword argument 'encoding'
...
```

I get some unrelated error coming out of the workflow, but that XML output looks valid and the workflow works for me. Do you see another error that prevents that XML output on your end?

**Comment by snooze92** [comment]
I'm on an M1 MAX laptop, with native arm64 Python packages in Conda starting only with 3.8... but I did install the x86_64 version of 3.7.4, and the workflow works as expected with that as well.

I'm afraid I cannot debug further on my end as I am unable to reproduce an issue. Let me know what you see when running e.g. `/usr/bin/python3 --version`, `/usr/bin/python3 epoch.py ""`, `python --version`, `python epoch.py ""`...

**Comment by leoleec** [comment]
Last login: Tue Jan 31 20:04:04 on ttys000

You have mail.


The default interactive shell is now zsh.

To update your account to use zsh, please run `chsh -s /bin/zsh`.

For more details, please visit https://support.apple.com/kb/HT208050.

(env_jupyter) jacob-MBP14-2021:~ jacob.lee$ python --version

Python 3.7.4

(env_jupyter) jacob-MBP14-2021:~ jacob.lee$ python3 --version

Python 3.10.6

(env_jupyter) jacob-MBP14-2021:~ jacob.lee$ python epoch.py ""

python: can't open file 'epoch.py': [Errno 2] No such file or directory

(env_jupyter) jacob-MBP14-2021:~ jacob.lee$ python3 epoch.py ""

/opt/homebrew/bin/python3: can't open file '/Users/jacob.lee/epoch.py':
[Errno 2] No such file or directory

(env_jupyter) jacob-MBP14-2021:~ jacob.lee$ pip install epoch

WARNING: pip is being invoked by an old script wrapper. This will fail in a
future version of pip.

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the
underlying issue.

To avoid this problem you can invoke Python with '-m pip' instead of
running pip directly.

Defaulting to user installation because normal site-packages is not
writeable

Requirement already satisfied: epoch in
./Library/Python/3.7/lib/python/site-packages (0.1.5)

Requirement already satisfied: pytz>=2013b in
./Library/Python/3.7/lib/python/site-packages (from epoch) (2022.7.1)

Requirement already satisfied: six>=1.4.1 in
./Library/Python/3.7/lib/python/site-packages (from epoch) (1.12.0)

(env_jupyter) jacob-MBP14-2021:~ jacob.lee$

2023년 1월 31일 (화) 오후 5:52, Julien Lehuen ***@***.***>님이 작성:

**Comment by leoleec** [comment]
python epoch.py ""
python: can't open file 'epoch.py': [Errno 2] No such file or directory

**Comment by leoleec** [comment]
@snooze92  I fixed it. It was my problem. Can you delete this thread?
