### ISSUE TITLE
Can the script be triggered without using ts?

### ISSUE THREAD

**Issue by lijiachang** [snooze92/alfred-epoch-converter#15]
same as：

<img width="650" alt="image" src="https://github.com/snooze92/alfred-epoch-converter/assets/28041718/7306b847-1e80-44ea-8175-e76b259ffda9">

I have tried several config，but not work

**Comment by snooze92** [comment]
I think you could try other triggers - e.g. a hotkey, but I think the keyword approach is best in this case.

**Comment by lijiachang** [comment]
Thank you for your reply
