### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by bebound** [snooze92/alfred-epoch-converter#3]
This script is useful, but I found some wrong result while using it.

`ts 1610334058037586000` returns `2021-01-11T03:00:58.3758592`.
The expected result is `2021-01-11T03:00:58.037586`

`ts 1585895927692008000` returns `2020-04-03T06:38:47.692007936`
The expected result is `2020-04-03T06:38:47.692008`

**Comment by snooze92** [comment]
Interesting, `ts 1610334058037586` gives the right result, but adding trailing 0s seems to throw the conversion off.

Have you found wrong results without trailing 0s as well?

Do you want to submit a fix? Otherwise I can look into it soon-ish.

**Comment by bebound** [comment]
`ts 1610334058037586` gives wrong result. The second should be `58.037` not `58.37`

Let me have a try. :)

**Comment by snooze92** [comment]
Seems like a bug I introduced when trying to managed sub-seconds properly, because of the way 0s are handled on either side... Let me know if you find anything, I'm happy to review any PR any time, or try to have a look myself!

**Comment by snooze92** [comment]
I've merged your request, it seems to work fine for me. Thank you!
